/**
 * Algeria's complete 69 wilayas — single source of truth.
 * Used by: order form, admin dashboard, i18n strings, Telegram notifications.
 */
export const ALGERIA_WILAYAS = [
  { code: '01', name: 'Adrar',                  arabic: 'أدرار' },
  { code: '02', name: 'Chlef',                   arabic: 'الشلف' },
  { code: '03', name: 'Laghouat',                arabic: 'الأغواط' },
  { code: '04', name: 'Oum El Bouaghi',          arabic: 'أم البواقي' },
  { code: '05', name: 'Batna',                   arabic: 'باتنة' },
  { code: '06', name: 'Béjaïa',                  arabic: 'بجاية' },
  { code: '07', name: 'Biskra',                  arabic: 'بسكرة' },
  { code: '08', name: 'Béchar',                  arabic: 'بشار' },
  { code: '09', name: 'Blida',                   arabic: 'البليدة' },
  { code: '10', name: 'Bouira',                  arabic: 'البويرة' },
  { code: '11', name: 'Tamanrasset',             arabic: 'تمنراست' },
  { code: '12', name: 'Tébessa',                 arabic: 'تبسة' },
  { code: '13', name: 'Tlemcen',                 arabic: 'تلمسان' },
  { code: '14', name: 'Tiaret',                  arabic: 'تيارت' },
  { code: '15', name: 'Tizi Ouzou',              arabic: 'تيزي وزو' },
  { code: '16', name: 'Alger',                   arabic: 'الجزائر' },
  { code: '17', name: 'Djelfa',                  arabic: 'الجلفة' },
  { code: '18', name: 'Jijel',                   arabic: 'جيجل' },
  { code: '19', name: 'Sétif',                   arabic: 'سطيف' },
  { code: '20', name: 'Saïda',                   arabic: 'سعيدة' },
  { code: '21', name: 'Skikda',                  arabic: 'سكيكدة' },
  { code: '22', name: 'Sidi Bel Abbès',          arabic: 'سيدي بلعباس' },
  { code: '23', name: 'Annaba',                  arabic: 'عنابة' },
  { code: '24', name: 'Guelma',                  arabic: 'قالمة' },
  { code: '25', name: 'Constantine',             arabic: 'قسنطينة' },
  { code: '26', name: 'Médéa',                   arabic: 'المدية' },
  { code: '27', name: 'Mostaganem',              arabic: 'مستغانم' },
  { code: '28', name: "M'Sila",                  arabic: 'المسيلة' },
  { code: '29', name: 'Mascara',                 arabic: 'معسكر' },
  { code: '30', name: 'Ouargla',                 arabic: 'ورقلة' },
  { code: '31', name: 'Oran',                    arabic: 'وهران' },
  { code: '32', name: 'El Bayadh',               arabic: 'البيض' },
  { code: '33', name: 'Illizi',                  arabic: 'إليزي' },
  { code: '34', name: 'Bordj Bou Arréridj',      arabic: 'برج بوعريريج' },
  { code: '35', name: 'Boumerdès',               arabic: 'بومرداس' },
  { code: '36', name: 'El Tarf',                 arabic: 'الطارف' },
  { code: '37', name: 'Tindouf',                 arabic: 'تندوف' },
  { code: '38', name: 'Tissemsilt',              arabic: 'تيسمسيلت' },
  { code: '39', name: 'El Oued',                 arabic: 'الوادي' },
  { code: '40', name: 'Khenchela',               arabic: 'خنشلة' },
  { code: '41', name: 'Souk Ahras',              arabic: 'سوق أهراس' },
  { code: '42', name: 'Tipaza',                  arabic: 'تيبازة' },
  { code: '43', name: 'Mila',                    arabic: 'ميلة' },
  { code: '44', name: 'Aïn Defla',               arabic: 'عين الدفلى' },
  { code: '45', name: 'Naâma',                   arabic: 'النعامة' },
  { code: '46', name: 'Aïn Témouchent',          arabic: 'عين تموشنت' },
  { code: '47', name: 'Ghardaïa',               arabic: 'غرداية' },
  { code: '48', name: 'Relizane',                arabic: 'غليزان' },
  { code: '49', name: 'Timimoune',               arabic: 'تيميمون' },
  { code: '50', name: 'Bordj Badji Mokhtar',     arabic: 'برج باجي مختار' },
  { code: '51', name: 'Ouled Djellal',           arabic: 'أولاد جلال' },
  { code: '52', name: 'In Salah',                arabic: 'عين صالح' },
  { code: '53', name: 'In Guezzam',              arabic: 'عين قزام' },
  { code: '54', name: 'Touggourt',               arabic: 'تقرت' },
  { code: '55', name: 'Djanet',                  arabic: 'جانت' },
  { code: '56', name: "El M'Ghair",              arabic: 'المغير' },
  { code: '57', name: 'Béni Abbès',              arabic: 'بني عباس' },
  { code: '58', name: 'El Meniaa',               arabic: 'المنيعة' },
  { code: '59', name: 'Aflou',                   arabic: 'أفلو' },
  { code: '60', name: 'Barika',                  arabic: 'بريكة' },
  { code: '61', name: 'Ksar Chellala',           arabic: 'قصر الشلالة' },
  { code: '62', name: 'Messaad',                 arabic: 'مسعد' },
  { code: '63', name: 'Aïn Oussara',             arabic: 'عين وسارة' },
  { code: '64', name: 'Bou Saâda',               arabic: 'بوسعادة' },
  { code: '65', name: 'El Abiodh Sidi Cheikh',   arabic: 'الأبيض سيدي الشيخ' },
  { code: '66', name: 'El Kantara',              arabic: 'القنطرة' },
  { code: '67', name: 'Bir El Ater',             arabic: 'بئر العاتر' },
  { code: '68', name: 'Ksar El Boukhari',        arabic: 'قصر البخاري' },
  { code: '69', name: 'El Aricha',               arabic: 'العريشة' },
] as const

/** Formatted label for dropdowns: "01 - Adrar" */
export const WILAYA_OPTIONS = ALGERIA_WILAYAS.map(
  w => `${w.code} - ${w.name}`
)

export type WilayaCode = typeof ALGERIA_WILAYAS[number]['code']
export type WilayaName = typeof ALGERIA_WILAYAS[number]['name']
